# Generated by Django 4.0 on 2022-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0004_remove_offer_polymorphic_ctype_and_more'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposed_match',
            name='offer_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposed_match',
            name='request_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposed_match',
            name='true_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='proposed_match',
            unique_together={('offer', 'request')},
        ),
        migrations.AlterUniqueTogether(
            name='true_match',
            unique_together={('offer', 'request')},
        ),
    ]
