# Generated by Django 4.0 on 2022-01-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferLike',
            new_name='Offer_Like',
        ),
        migrations.RenameModel(
            old_name='TrueMatch',
            new_name='Proposed_Match',
        ),
        migrations.RenameModel(
            old_name='RequestLike',
            new_name='Request_Like',
        ),
        migrations.RenameModel(
            old_name='ProposedMatch',
            new_name='True_Match',
        ),
    ]
