# Generated by Django 4.0 on 2022-02-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_proposed_match_offer_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_like',
            name='received_like_from_offer',
        ),
        migrations.RemoveField(
            model_name='request_like',
            name='request',
        ),
        migrations.RemoveField(
            model_name='request_like',
            name='sent_like_to_offer',
        ),
        migrations.AlterUniqueTogether(
            name='true_match',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='true_match',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='true_match',
            name='request',
        ),
        migrations.DeleteModel(
            name='Offer_Like',
        ),
        migrations.DeleteModel(
            name='Request_Like',
        ),
        migrations.DeleteModel(
            name='True_Match',
        ),
    ]
