# Generated by Django 4.0 on 2022-01-10 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 10, 22, 27, 37, 705271, tzinfo=utc))),
                ('zip_code', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('street_number', models.IntegerField()),
                ('living_area', models.IntegerField()),
                ('monthly_rent_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('num_other_tennants', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='request')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertions.room', verbose_name='object id')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insertions.objecttype', verbose_name='object type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='offer')),
            ],
            options={
                'unique_together': {('user_id', 'object_id')},
            },
        ),
    ]
