# Generated by Django 4.0 on 2022-02-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_address',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insertions.offer'),
        ),
        migrations.AlterField(
            model_name='object_address',
            name='request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insertions.request'),
        ),
    ]
