# Generated by Django 4.0 on 2022-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='short_description',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.CharField(default='test-title', max_length=127),
            preserve_default=False,
        ),
    ]
