# Generated by Django 4.0 on 2022-01-10 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 10, 22, 29, 3, 373473, tzinfo=utc)),
        ),
    ]
