# Generated by Django 4.0 on 2022-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='matches',
            field=models.ManyToManyField(to='insertions.Offer'),
        ),
    ]
