# Generated by Django 4.0 on 2022-01-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heating_type',
            old_name='name',
            new_name='type_name',
        ),
    ]
