# Generated by Django 4.0 on 2022-01-10 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('insertions', '0002_rename_user_id_offer_user_alter_room_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='object_id',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 10, 22, 31, 40, 277749, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('user', 'object')},
        ),
    ]
