# Generated by Django 4.0 on 2022-02-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0002_alter_object_address_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object_address',
            options={'verbose_name': 'object_address'},
        ),
    ]
