# Generated by Django 4.0 on 2022-01-10 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0003_rename_object_id_offer_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectType',
            new_name='Object_Type',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 10, 22, 35, 28, 97094, tzinfo=utc)),
        ),
    ]
