# Generated by Django 4.0 on 2022-01-10 23:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0004_rename_objecttype_object_type_alter_room_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='object_type',
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 10, 23, 15, 17, 450328, tzinfo=utc))),
                ('zip_code', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('street_number', models.IntegerField()),
                ('living_area', models.IntegerField()),
                ('monthly_rent_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insertions.object_type', verbose_name='object type')),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertions.object', verbose_name='object id'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
