# Generated by Django 4.0 on 2022-01-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0004_rename_matches_request_offer_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='offer_matches',
        ),
    ]
