# Generated by Django 4.0 on 2022-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0005_remove_offer_object_type_object_alter_offer_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='living_area',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='object',
            name='street_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='object',
            name='zip_code',
            field=models.IntegerField(default=-1),
        ),
    ]
